In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# import shutil
# source_path=r'D:\Programming\Cognifyz\ML\Restraunt_Pred\data\unprocessed\Dataset .csv'
# destination_path=r'D:\Programming\Cognifyz\ML\Restraunt_Pred\data\processed\Dataset .csv'

# shutil.copy(source_path,destination_path)

In [3]:
# Loading the csv file
import pandas as pd

df = pd.read_csv(r'/Dataset .csv')
df.head(10)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),No,No,No,No,3,4.4,Green,Very Good,336
6,6300781,Buffet 101,162,Pasay City,"Building K, SM By The Bay, Sunset Boulevard, M...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979667,14.531333,"Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.0,Green,Very Good,520
7,6301290,Vikings,162,Pasay City,"Building B, By The Bay, Seaside Boulevard, Mal...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979333,14.540000,"Seafood, Filipino, Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.2,Green,Very Good,677
8,6300010,Spiral - Sofitel Philippine Plaza Manila,162,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, Pasay City","Sofitel Philippine Plaza Manila, Pasay City, P...",120.980090,14.552990,"European, Asian, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.9,Dark Green,Excellent,621
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,532

In [4]:
null_values = df.isnull().sum()
values_na= df.isna().sum()
nmv = df.notnull().sum()
print(f"The null values is:\n{null_values}")
print(f"The inputs with N/A:\n{values_na}")
print(f"Value:\n{nmv}")

The null values is:
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64
The inputs with N/A:
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64
Value:
Restaurant ID           9551
Restaurant Name         9551
Country Code            9551
City                    9551
Address                 9551
Locality                9551
Locality Verbose        9551
Longitude               9551
Latitude                9551
Cuisines                9542
Average Cost for two    9551
Currency                9551
Has Table booking       9551
Has Online delivery     9551
Is delivering now       9551
Switch to order menu    9551
Price range             9551
Aggregate rating        9551
Rating color            9551
Rating text             9551
Votes                   9551
dtype: int64

In [5]:
# import pandas as pd

# try:

#     df = pd.read_csv(r'D:\Programming\Cognifyz\ML\Restraunt_Pred\data\processed\Dataset .csv', na_values=["N/A", "n/a", "NA", "na", "null", "NULL", ""])

#     # Detect missing values
#     print("Missing values per column:")
#     print(df.isna().sum())
#     missing_rows = df[df.isna().any(axis=1)]
#     print("\nRows with missing values:")
#     print(missing_rows)

# except FileNotFoundError:
#     print("Error: CSV file not found.")
# except pd.errors.EmptyDataError:
#     print("Error: CSV file is empty.")
# except Exception as e:
#     print(f"An error occurred: {e}")


import pandas as pd

try:
    df = pd.read_csv(r'D:\Programming\Cognifyz\ML\Restraunt_Pred\data\processed\Dataset .csv')
except FileNotFoundError:
    print("Error: CSV file not found.")
    exit()
except pd.errors.EmptyDataError:
    print("Error: CSV file is empty.")
    exit()

# # Display the DataFrame
print("DataFrame:\n", df)

# # Detect missing values (True where NaN exists)
print("\nMissing value mask:\n", df.isna())

# Detect rows with any NaN values
rows_with_na = df[df.isna().any(axis=1)]
print("\nRows containing NaN values:\n", rows_with_na)

# Detect columns with any NaN values
cols_with_na = df.columns[df.isna().any()].tolist()
print("\nColumns containing NaN values:", cols_with_na)

# Detect rows with NO NaN values
rows_without_na = df[df.notna().all(axis=1)]
print("\nRows without NaN values:\n", rows_without_na)

# # Detect columns with NO NaN values
# cols_without_na = df.columns[df.notna().all()].tolist()
# print("\nColumns without NaN values:", cols_without_na)

Error: CSV file not found.
DataFrame:
       Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208         ��stanbul
9547        5908749              Ceviz A��ac۱           208         ��stanbul
9548        5915807                     Huqqa           208         ��stanbul
9549        5916112               A���k Kahve           208         ��stanbul
9550        5927402  Walter's Coffee Roastery           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]

Missing value mask:
       Restaurant ID  Restaurant Name  Country Code   City  Address  Locality  \
0             False            False         False  False    False     False
1             False            False         False  False    False     False
2             False            False         False  False    False     False
3             False            False         False  False    False     False
4             False            False         False  False    False     False
...             ...              ...           ...    ...      ...       ...
9546          False            False         False  False    False     False
9547          False            False         False  False    False     False
9548          False            False         False  False    False     False
9549          False            False         False  False    False     False
9550          False            False         False  False    False     False

      Locality Verbose  Longitude  Latitude  Cuisines  ...  Currency  \
0                False      False     False     False  ...     False
1                False      False     False     False  ...     False
2                False      False     False     False  ...     False
3                False      False     False     False  ...     False
4                False      False     False     False  ...     False
...                ...        ...       ...       ...  ...       ...
9546             False      False     False     False  ...     False
9547             False      False     False     False  ...     False
9548             False      False     False     False  ...     False
9549             False      False     False     False  ...     False
9550             False      False     False     False  ...     False

      Has Table booking  Has Online delivery  Is delivering now  \
0                 False                False              False
1                 False                False              False
2                 False                False              False
3                 False                False              False
4                 False                False              False
...                 ...                  ...                ...
9546              False                False              False
9547              False                False              False
9548              False                False              False
9549              False                False              False
9550              False                False              False

      Switch to order menu  Price range  Aggregate rating  Rating color  \
0                    False        False             False         False
1                    False        False             False         False
2                    False        False             False         False
3                    False        False             False         False
4                    False        False             False         False
...                    ...          ...               ...           ...
9546                 False        False             False         False
9547                 False        False             False         False
9548                 False        False             False         False
9549                 False        False             False         False
9550                 False        False             False         False

      Rating text  Votes
0           False  False
1           False  False
2           False  False
3           False  False
4           False  False
...           ...    ...
9546        False  False
9547        False  False
9548        False  False
9549        False  False
9550        False  False

[9551 rows x 21 columns]

Rows containing NaN values:
      Restaurant ID                 Restaurant Name  Country Code  \
84        17284105                   Cookie Shoppe           216
87        17284211  Pearly's Famous Country Cookng           216
94        17284158               Jimmie's Hot Dogs           216
297       17374552                  Corkscrew Cafe           216
328       17501439                        Dovetail           216
346       17606621            HI Lite Bar & Lounge           216
368       17059060                       Hillstone           216
418       17142698                Leonard's Bakery           216
455       17616465        Tybee Island Social Club           216

               City                                          Address  \
84           Albany               115 N Jackson St, Albany, GA 31701
87           Albany             814 N Slappey Blvd, Albany, GA 31701
94           Albany               204 S Jackson St, Albany, GA 31701
297     Gainesville                51 W Main St, Dahlonega, GA 30533
328           Macon                   543 Cherry St, Macon, GA 31201
346          Miller             109 N Broadway Ave, Miller, SD 57362
368         Orlando  215 South Orlando Avenue, Winter Park, FL 32789
418  Rest of Hawaii             933 Kapahulu Ave, Honolulu, HI 96816
455        Savannah          1311 Butler Ave, Tybee Island, GA 31328

         Locality         Locality Verbose   Longitude   Latitude Cuisines  \
84         Albany           Albany, Albany  -84.154000  31.577200      NaN
87         Albany           Albany, Albany  -84.175900  31.588200      NaN
94         Albany           Albany, Albany  -84.153400  31.575100      NaN
297     Dahlonega   Dahlonega, Gainesville  -83.985800  34.531800      NaN
328         Macon             Macon, Macon  -83.627979  32.836410      NaN
346        Miller           Miller, Miller  -98.989100  44.515800      NaN
368   Winter Park     Winter Park, Orlando  -81.365260  28.596682      NaN
418       Kaimuki  Kaimuki, Rest of Hawaii -157.813432  21.284586      NaN
455  Tybee Island   Tybee Island, Savannah  -80.848297  31.995810      NaN

     ...   Currency Has Table booking Has Online delivery Is delivering now  \
84   ...  Dollar($)                No                  No                No
87   ...  Dollar($)                No                  No                No
94   ...  Dollar($)                No                  No                No
297  ...  Dollar($)                No                  No                No
328  ...  Dollar($)                No                  No                No
346  ...  Dollar($)                No                  No                No
368  ...  Dollar($)                No                  No                No
418  ...  Dollar($)                No                  No                No
455  ...  Dollar($)                No                  No                No

    Switch to order menu Price range  Aggregate rating  Rating color  \
84                    No           1               3.4        Orange
87                    No           1               3.4        Orange
94                    No           1               3.9        Yellow
297                   No           3               3.9        Yellow
328                   No           3               3.8        Yellow
346                   No           1               3.4        Orange
368                   No           3               4.4         Green
418                   No           1               4.7    Dark Green
455                   No           1               3.9        Yellow

    Rating text Votes
84      Average    34
87      Average    36
94         Good   160
297        Good   209
328        Good   102
346     Average    11
368   Very Good  1158
418   Excellent   707
455        Good   309

[9 rows x 21 columns]

Columns containing NaN values: ['Cuisines']

Rows without NaN values:
       Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208         ��stanbul
9547        5908749              Ceviz A��ac۱           208         ��stanbul
9548        5915807                     Huqqa           208         ��stanbul
9549        5916112               A���k Kahve           208         ��stanbul
9550        5927402  Walter's Coffee Roastery           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9542 rows x 21 columns]

In [6]:
df[df['Rating text'].isna()][['Aggregate rating', 'Rating text', 'Rating color', 'Votes']].head(10)

Empty DataFrame
Columns: [Aggregate rating, Rating text, Rating color, Votes]
Index: []

In [7]:
print(df.shape)
print(df.columns)
print(df.isnull().sum())

(9551, 21)
Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [8]:
print(type(values_na))
print(values_na)

<class 'pandas.core.series.Series'>
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [9]:
print(df.isnull().sum())
print("----------------")
print(df.isna().sum())

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64
----------------
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [4]:
print("isnull")
print(df.isnull().sum().to_string())

print("\nisna")
print(df.isna().sum().to_string())

isnull
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0

isna
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0

In [5]:
df[df['Cuisines'].isnull()][['Restaurant Name', 'City', 'Address', 'Cuisines']]

,Restaurant Name,City,Address,Cuisines
84,Cookie Shoppe,Albany,"115 N Jackson St, Albany, GA 31701",NaN
87,Pearly's Famous Country Cookng,Albany,"814 N Slappey Blvd, Albany, GA 31701",NaN
94,Jimmie's Hot Dogs,Albany,"204 S Jackson St, Albany, GA 31701",NaN
297,Corkscrew Cafe,Gainesville,"51 W Main St, Dahlonega, GA 30533",NaN
328,Dovetail,Macon,"543 Cherry St, Macon, GA 31201",NaN
346,HI Lite Bar & Lounge,Miller,"109 N Broadway Ave, Miller, SD 57362",NaN
368,Hillstone,Orlando,"215 South Orlando Avenue, Winter Park, FL 32789",NaN
418,Leonard's Bakery,Rest of Hawaii,"933 Kapahulu Ave, Honolulu, HI 96816",NaN
455,Tybee Island Social Club,Savannah,"1311 Butler Ave, Tybee Island, GA 31328",NaN

In [6]:
df.dropna(subset=['Cuisines'], inplace=True)

In [7]:
print(df.isnull().sum())

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9542 non-null   int64
 1   Restaurant Name       9542 non-null   object
 2   Country Code          9542 non-null   int64
 3   City                  9542 non-null   object
 4   Address               9542 non-null   object
 5   Locality              9542 non-null   object
 6   Locality Verbose      9542 non-null   object
 7   Longitude             9542 non-null   float64
 8   Latitude              9542 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9542 non-null   int64
 11  Currency              9542 non-null   object
 12  Has Table booking     9542 non-null   object
 13  Has Online delivery   9542 non-null   object
 14  Is delivering now     9542 non-null   object
 15  Switch to order menu  9542 non-null   object
 16  Price range           9542 non-null   int64
 17  Aggregate rating      9542 non-null   float64
 18  Rating color          9542 non-null   object
 19  Rating text           9542 non-null   object
 20  Votes                 9542 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.6+ MB

In [10]:
for col in df.columns:
    print(col, ":", df[col].nunique())

Restaurant ID : 9542
Restaurant Name : 7437
Country Code : 15
City : 140
Address : 8910
Locality : 1206
Locality Verbose : 1263
Longitude : 8111
Latitude : 8668
Cuisines : 1825
Average Cost for two : 140
Currency : 12
Has Table booking : 2
Has Online delivery : 2
Is delivering now : 2
Switch to order menu : 1
Price range : 4
Aggregate rating : 33
Rating color : 6
Rating text : 6
Votes : 1012

In [ ]:
drop_cols=['Restaurant ID', 'Restaurant Name', 'Address', 'Locality', 'Locality Verbose', 'City', 'Country Code', 'Rating color','Rating text']
df.drop(columns=drop_cols, inplace=True)

In [ ]:
# pip install scikit-learn

In [11]:
# Feature Engineering
import sklearn
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

df['Cuisines_Count']=df['Cuisines'].apply(lambda x: x.split(','))

mlb = MultiLabelBinarizer()

cuisines_encoded = mlb.fit_transform(df['Cuisines'].str.split(','))

cuisines_df = pd.DataFrame(cuisines_encoded, columns=[f'Cuisine_{c}' for c in mlb.classes_], index=df.index)

df = pd.concat(
    [
        df.drop(columns=['Cuisines']),
        cuisines_df
    ],
    axis=1
)

In [ ]:
# Log Transformation of Votes

In [ ]:
import numpy as np
df['Log_Votes'] = np.log1p(df['Votes'])

In [ ]:
import numpy as np
df['Cost_Price_Level']=(df['Average Cost for two'] / df['Price range'].replace(0, np.nan))
df['Cost_Price_Level'] =(df['Cost_Price_Level'].fillna(0))

In [13]:
# Encoding cat features
cat_cols={'Has Table booking',
'Has Online delivery',
'Is delivering now'
}
df['Has Table booking']= df['Has Table booking'].replace({'Yes': 1, 'No': 0})

df['Has Online delivery']= df['Has Online delivery'].replace({'Yes': 1, 'No': 0})

df['Is delivering now']= df['Is delivering now'].replace({'Yes': 1, 'No': 0})

In [14]:
for col in ['Has Table booking',
            'Has Online delivery',
            'Is delivering now']:
    print(col)
    print(df[col].value_counts(dropna=False))

Has Table booking
Has Table booking
0    8384
1    1158
Name: count, dtype: int64
Has Online delivery
Has Online delivery
0    7091
1    2451
Name: count, dtype: int64
Is delivering now
Is delivering now
0    9508
1      34
Name: count, dtype: int64

In [ ]:
# # df[['Has Table booking',
# # 'Has Online delivery',
# # 'Is delivering now'
# # ]].head()


# # # print(df[['Has Table booking',
# # # 'Has Online delivery',
# # # 'Is delivering now'
# # # ]].dtypes)

# print(df[['Has Table booking',
#           'Has Online delivery',
#           'Is delivering now']].dtypes)

In [15]:
# # for col in ['Has Table booking', 'Has Online delivery', 'Is delivering now']:
# #     print(f"\n{col}")
# #     print(df[col].value_counts(dropna=False))

binary_cols = [
    'Has Table booking',
    'Has Online delivery',
    'Is delivering now'
]

df[binary_cols] = df[binary_cols].astype(int)

print(df[binary_cols].dtypes)

Has Table booking      int64
Has Online delivery    int64
Is delivering now      int64
dtype: object

In [ ]:
# One-Hot encoding for 'Currency' column